### ISSUE TITLE
Extension prevents posting of replies

### ISSUE THREAD

**Issue by vvt4** [HamletDuFromage/4chan-mass-reply#27]
I don't know if 4chan is able to detect this extension specifically somehow (because JKCS works fine), but while this extension is active you will not be able to post replies or create threads on 4chan.
**Expected behaviour**
(Captcha magically solves itself, you just hit enter) You manually type in the captcha because the captcha solvers are going fucking haywire with the new captcha, you press enter and your reply is sent.
**Actual behaviour**
4chanx reports "You have mistyped....CAPTCHA has malfunctioned" error.

I've tried posting with disabling both jkcs and 4chmr, I was able to post. I enabled jkcs and disabled 4chmr, I was able to post. I disabled jkcs and enabled 4chmr, I am unable to post and the error is shown. The problem lies with this extension.

**Comment by vvt4** [comment]
>What browser
firefox v123.0b8, arkenfox tweaks with some user overrides allowing for a more day to day browsing experience
>What os
Windows 11

Yes the error persists on a new clean browser profile. What options are you using? I'm using these 
![image](https://github.com/HamletDuFromage/4chan-mass-reply/assets/155285435/118e6526-8010-4609-929e-903c2a7f3587)

**Comment by vvt4** [comment]
welp looks like disabling ban evasion bypass seems to fix the issue.

**Comment by HamletDuFromage** [comment]
> welp looks like disabling ban evasion bypass seems to fix the issue.

ah yeah, that'll do it. I had it disabled since way back it wouldn't let you post, but I might just remove it altogether

**Comment by HamletDuFromage** [comment]
@soyware Are you interested in looking into it? That was your commit, right? I can't remember.
I'll give it a go if you don't

**Comment by soyware** [comment]
looks like it happens because of different user-agent between /captcha and /cdn-cgi/challenge-platform/ requests, amma come up with something

**Comment by soyware** [comment]
@HamletDuFromage you can merge my fork and check if everything works fine

**Comment by sirius-sama** [comment]
I'd like to know how this "Bypass ban revision detection" works. 
Does it send the wrong IP/info/or something to the server?

**Comment by HamletDuFromage** [comment]
merged @soyware 's changes, looks like its working



> I'd like to know how this "Bypass ban evasion detection" works. Does it send the wrong IP/info/or something to the server?
> 
> Edit: tooltips say it'll strip chan_pass and cookie and ... Is this feature only for those who have pass?

if you're banned and change your ip, you'll still have the cookies from when you got banned and 4channel well realize you're ban evading. Stripping the cookies when you post means you can bypass the ban evasion detection
