### ISSUE TITLE
No more chrome releases?

### ISSUE THREAD

**Issue by ripandtearr** [HamletDuFromage/4chan-mass-reply#29]
Unpacked .zip is missing from the last release

I'd be happy to generate my own if there's any documentation on how to do it

**Comment by HamletDuFromage** [comment]
Oh yeah that's right, I forgot to include it. I use Firefox and it's been so long that I forgot all about it

I'll upload it later today but you can of course build it yourself with the npm commands from the readme and running createxpi.sh but I'll

**Comment by HamletDuFromage** [comment]
Added in latest release
