### ISSUE TITLE
Mass reply in wrong order

### ISSUE THREAD

**Issue by soyneed** [HamletDuFromage/4chan-mass-reply#34]
The 'Maximize Line Count' mass reply format seems to be in a reversed order, quoting from bottom to top.

**Comment by soyware** [comment]
that's the point, i think it funnier @HamletDuFromage

**Comment by soyneed** [comment]
>it's a feature not a bug

![Pointing markiplier fast](https://github.com/HamletDuFromage/4chan-mass-reply/assets/163203365/00030705-0759-4bb8-a662-b82285e1a5fe)
