### ISSUE TITLE
Add random timestamp filenames and image hash randomizer

### ISSUE THREAD

**Issue by pixelplanetdev** [HamletDuFromage/4chan-mass-reply#5]
It could be just one checkbox, i got one userscript for it

https://gist.github.com/pixelplanetdev/65f8661b528ad94095089c7bed024f80

It does randomize the hash by changing random pixels and recompressing it. It also allows webp to get uploaded to 4chan, because of the recompression.

**Comment by HamletDuFromage** [comment]
That sounds like a good idea. Is it your code? What's the license on it?

**Comment by pixelplanetdev** [comment]
it's my code, do whatever you want with it, consider it public domain

**Comment by HamletDuFromage** [comment]
I've implemented it, thanks for the code! Could you look at the commit to make sure I didn't do anything too egregious? I'm very new to javascript

**Comment by pixelplanetdev** [comment]
Looks ok. As long as it works.
Thanks.
