### ISSUE TITLE
Strip cookies from post request

### ISSUE THREAD

**Issue by pixelplanetdev** [HamletDuFromage/4chan-mass-reply#6]
Instead of manually deleting the cookies with a button when ban evading, we might just strip the cookies from every posting request.
Something like using [onBeforeSendHeaders](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders) filtered on the  https://sys.4channel.org/*/post requests and removing the Cookie Header.

If i got this right, this means that cookies are still being kept, like for the theme, but we don't have to bother deleting them on bans anymore.
The downside is that we can't use 4chan passes... but why would someone pay money to 4cuck anyway?

**Comment by HamletDuFromage** [comment]
wouldn't it complain if it doesn't have the same cookies the captcha was completed with?
t. clueless on web

**Comment by pixelplanetdev** [comment]
i have no idea, we could strip it from the captcha too

**Comment by pixelplanetdev** [comment]
checked it and the captcha is sent in the POST fields, so i do not think that it needs the same cookies

**Comment by HamletDuFromage** [comment]
https://github.com/HamletDuFromage/4chan-mass-reply/commit/a3914476f01103891f3bec49e89b2dd6feabee6b#diff-25daee2bd4a749c171c5bd0b87567f3fe306a1fdacb2a6d6785a3e1e6fd065f9R29-R39

It correctly changes the cookies of GET requests, but not POST. Again, I have very little understanding of what I'm doing, any idea?

**Comment by pixelplanetdev** [comment]
the post request is on sys.4chan(nel).org

```

browser.webRequest.onBeforeSendHeaders.addListener((item) => {
    for (var header of item.requestHeaders) {
        if (header.name.toLowerCase() === "cookie") {
            console.log(header.value);
            header.value = '';
        }
    }
    return { requestHeaders: item.requestHeaders }; 

}, { urls: ["*://sys.4channel.org/*/post", "*://sys.4chan.org/*/post"] }, ["blocking", "requestHeaders", "extraHeaders"]); 
```
extraHeaders is apparently needed for Chrome
